sonar.projectKey=martyr-rrr_python-project-49
sonar.organization=martyr-rrr
sonar.projectName=Python Project 49
sonar.sources=brain_games
sonar.language=py
sonar.python.version=3.12
sonar.login=${env.SONAR_TOKEN}
sonar.host.url=https://sonarcloud.io
